name: Test

on: [push]

jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - run: npm run test
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - run: npm run build
